### ISSUE TITLE
size don't match (606,602)

### ISSUE THREAD

**Issue by zmskye** [ratishsp/data2text-entity-py#2]
Hi, when I use your code, there is a problem, it's "Not all arguments have the same value:", which is caused by `aeq(sourceL, src_len)` in GlobalAttention.py. And I find that length of entities_list and  src data , which is 602 and 606 respectively. Apparently, this is because of `<unk>,<blank>,</s> and <s>.` But when I restrict the length of src data to 602, the model could run normally, but the score of RG/CS/CO is too low. 

Please help me .

**Comment by ratishsp** [comment]
Should be fixed by the commit https://github.com/ratishsp/data2text-entity-py/commit/d46fe717c98cd8c76930f3d4fb257c10cd840035
