### ISSUE TITLE
Question about evalution with torch

### ISSUE THREAD

**Issue by LiuYixian** [ratishsp/data2text-entity-py#3]
Hi,

When I run the evalution with 
`CUDA_VISIBLE_DEVICES=6 ~/torch/install/bin/th extractor.lua -gpuid 1 -datafile roto-ie.h5 -preddata drive_data/transform_gen/roto_cc-beam5_gens.h5 -dict_pfx "roto-ie" -just_eval`, I'm faced with the following error.
`/root/torch/install/bin/luajit: extractor.lua:574: bad argument #1 to 'copy' (sizes do not match at /root/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)`
I print the size and find that the size of p (parameters of generated model) is 2234733, and the size of saved_p (parameters from conv1ie-ep6-94-74.t7) is 2141733. How can I solve the problem?

My torch is installed with LuaJIT. The hdf5 is installed with 'luarocks install hdf5'.

Thank you

Yixian

**Comment by huanghonggit** [comment]
hi, how did you run this code?  I am  don't understand the Dateset introduction in README and also can't find the create_dataset.py in scripts folder? 

Thank you

**Comment by FXLP** [comment]
> hi, how did you run this code? I am don't understand the Dateset introduction in README and also can't find the create_dataset.py in scripts folder?
> 
> Thank you
Me too, I downloaded the three json files of rotowire but I don’t know how to construct the dataset, did you solve it?

**Comment by DrLiLiang** [comment]
> hi, how did you run this code? I am don't understand the Dateset introduction in README and also can't find the create_dataset.py in scripts folder?
> 
> Thank you
> Me too, I downloaded the three json files of rotowire but I don’t know how to construct the dataset, did you solve it?

https://github.com/ratishsp/data2text-plan-py

**Comment by liang8qi** [comment]
> Hi,
> 
> When I run the evalution with
> `CUDA_VISIBLE_DEVICES=6 ~/torch/install/bin/th extractor.lua -gpuid 1 -datafile roto-ie.h5 -preddata drive_data/transform_gen/roto_cc-beam5_gens.h5 -dict_pfx "roto-ie" -just_eval`, I'm faced with the following error.
> `/root/torch/install/bin/luajit: extractor.lua:574: bad argument #1 to 'copy' (sizes do not match at /root/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)`
> I print the size and find that the size of p (parameters of generated model) is 2234733, and the size of saved_p (parameters from conv1ie-ep6-94-74.t7) is 2141733. How can I solve the problem?
> 
> My torch is installed with LuaJIT. The hdf5 is installed with 'luarocks install hdf5'.
> 
> Thank you
> 
> Yixian


> Hi,
> 
> When I run the evalution with
> `CUDA_VISIBLE_DEVICES=6 ~/torch/install/bin/th extractor.lua -gpuid 1 -datafile roto-ie.h5 -preddata drive_data/transform_gen/roto_cc-beam5_gens.h5 -dict_pfx "roto-ie" -just_eval`, I'm faced with the following error.
> `/root/torch/install/bin/luajit: extractor.lua:574: bad argument #1 to 'copy' (sizes do not match at /root/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)`
> I print the size and find that the size of p (parameters of generated model) is 2234733, and the size of saved_p (parameters from conv1ie-ep6-94-74.t7) is 2141733. How can I solve the problem?
> 
> My torch is installed with LuaJIT. The hdf5 is installed with 'luarocks install hdf5'.
> 
> Thank you
> 
> Yixian

hi, I met the same problem as you. Have you solved it?

**Comment by ratishsp** [comment]
Hi,
For RotoWire, the ie h5, dict and labels files are shared at https://drive.google.com/drive/folders/1akm3bAPlK2D9I_8q0w2ByrAjaPmfHHWC?usp=sharing
For MLB, the ie files are shared at https://drive.google.com/drive/folders/1n8hljpAyYNQV7Ut5fSSCfV1rasofNxYd?usp=sharing
