### ISSUE TITLE
create_dataset.py not found in boxscore-data repo

### ISSUE THREAD

**Issue by AnkiBhatia** [ratishsp/data2text-entity-py#4]
In the DataSet Section of the ReadMe.
I could not find the file "create_dataset.py" in the [boxscore-data](https://github.com/harvardnlp/boxscore-data/tree/master/scripts) 
mentioned in 
"The input dataset for data2text-plan-py can be created by running the script create_dataset.py in scripts folder."

**Comment by jianwei2017** [comment]
> In the DataSet Section of the ReadMe.
> I could not find the file "create_dataset.py" in the [boxscore-data](https://github.com/harvardnlp/boxscore-data/tree/master/scripts)
> mentioned in
> "The input dataset for data2text-plan-py can be created by running the script create_dataset.py in scripts folder."

It seems that the input dataset can only be downloaded in this website: https://drive.google.com/open?id=1GvFBVvOa2YPy_X9aJ6KYLoz_CnqZN796.
