### ISSUE TITLE
Script for creating txt files from json for MLB

### ISSUE THREAD

**Issue by ashishu007** [ratishsp/data2text-entity-py#6]
Hi @ratishsp,

Is it possible to upload the code for creating txt files for training/validation/testing for MLB data?
Something similar to this: https://github.com/ratishsp/data2text-entity-py/blob/master/scripts/create_dataset.py

And also, script for the template-based system on MLB dataset.

Thanks in advance.

**Comment by ratishsp** [comment]
Hi Ashish,
I think this is the relevant script https://github.com/ratishsp/mlb-data-scripts/blob/master/data2text_input_formatter.py for creating the txt files.
I will find the script for template-based system for MLB.

**Comment by ashishu007** [comment]
Thanks Ratish, appreciate it.

**Comment by ratishsp** [comment]
I have shared the model test outputs including template based system https://drive.google.com/drive/folders/1se11m-3q6Ra7ft2kSv69PHRZh0H2IiCW?usp=sharing
I am yet to find the script which generates this template output. But you should be able to reverse engineer the script from the template outputs.

**Comment by ashishu007** [comment]
Thanks again Ratish, this is very helpful. 

I think I am able to reverse engineer it as well. Just to be sure, you discuss 'all the pitchers' and 'all the batters who scored runs' from the game in a summary.

I'm closing the issue now. But if you ever find out the code, pls do share it in the repo.

**Comment by ratishsp** [comment]
I have committed the script to create the template output.
